### ISSUE TITLE
[Question] 4GB Tg Upload Support 

### ISSUE THREAD

**Issue by MuhammadBayiz** [X-Gorn/X-URL-Uploader#24]
Hi! I'm looking for a bot that can upload files up to 4GB in telegram, i have premium account but most of the bot can't upload more than 2GB

**Comment by iSaulX** [comment]
Hi, this isn't possible cuz telegram just upgrade premium accounts uploads to 4gb, but they forgot about bots, and even  you've a premium account, your bots won't be able to upload files bigger than 4GB. I hope my answers is that you're looking for.
